title:       "Operating Systems 2021-1 (OS211)"
version:     "0029---02-Mar-2021"
copyright:   "2021-2021"
description: >- 
  This is my OS 2021 web
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Nadya Aprillia"
address:          "Palembang"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://Pinatnat.github.io/os211-sandbox-web/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/Pinatnat/os211-sandbox-web/"
urlghpage:        "https://Pinatnat.github.io/os211-sandbox-web/"
keywords:         "jekyll, testing"
github:           [metadata]

